version: "3.9"
services:
  web:
    build: .
    ports:
      - "2565:2565"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://root:1234@db/kbgt?sslmode=disable
      PORT: :2565
  db:
    image: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 60s
      retries: 5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: kbgt
